/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedUpgradeRouteImport } from './routes/_authed/upgrade'
import { Route as AuthedTrialRouteImport } from './routes/_authed/trial'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedHomeRouteImport } from './routes/_authed/home'
import { Route as AuthedRecipesIndexRouteImport } from './routes/_authed/recipes.index'
import { Route as AuthedPantryIndexRouteImport } from './routes/_authed/pantry.index'
import { Route as AuthedCookIndexRouteImport } from './routes/_authed/cook.index'
import { Route as AuthedRecipesRecipeIdRouteImport } from './routes/_authed/recipes.$recipeId'
import { Route as AuthedPantryNewRouteImport } from './routes/_authed/pantry.new'
import { Route as AuthedPantryItemIdRouteImport } from './routes/_authed/pantry.$itemId'
import { Route as AuthedCookSessionRouteImport } from './routes/_authed/cook.session'
import { Route as AuthedCookGenerateRouteImport } from './routes/_authed/cook.generate'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedUpgradeRoute = AuthedUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTrialRoute = AuthedTrialRouteImport.update({
  id: '/trial',
  path: '/trial',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHomeRoute = AuthedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRecipesIndexRoute = AuthedRecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPantryIndexRoute = AuthedPantryIndexRouteImport.update({
  id: '/pantry/',
  path: '/pantry/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCookIndexRoute = AuthedCookIndexRouteImport.update({
  id: '/cook/',
  path: '/cook/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRecipesRecipeIdRoute = AuthedRecipesRecipeIdRouteImport.update({
  id: '/recipes/$recipeId',
  path: '/recipes/$recipeId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPantryNewRoute = AuthedPantryNewRouteImport.update({
  id: '/pantry/new',
  path: '/pantry/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPantryItemIdRoute = AuthedPantryItemIdRouteImport.update({
  id: '/pantry/$itemId',
  path: '/pantry/$itemId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCookSessionRoute = AuthedCookSessionRouteImport.update({
  id: '/cook/session',
  path: '/cook/session',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCookGenerateRoute = AuthedCookGenerateRouteImport.update({
  id: '/cook/generate',
  path: '/cook/generate',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/home': typeof AuthedHomeRoute
  '/settings': typeof AuthedSettingsRoute
  '/trial': typeof AuthedTrialRoute
  '/upgrade': typeof AuthedUpgradeRoute
  '/cook/generate': typeof AuthedCookGenerateRoute
  '/cook/session': typeof AuthedCookSessionRoute
  '/pantry/$itemId': typeof AuthedPantryItemIdRoute
  '/pantry/new': typeof AuthedPantryNewRoute
  '/recipes/$recipeId': typeof AuthedRecipesRecipeIdRoute
  '/cook/': typeof AuthedCookIndexRoute
  '/pantry/': typeof AuthedPantryIndexRoute
  '/recipes/': typeof AuthedRecipesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/home': typeof AuthedHomeRoute
  '/settings': typeof AuthedSettingsRoute
  '/trial': typeof AuthedTrialRoute
  '/upgrade': typeof AuthedUpgradeRoute
  '/cook/generate': typeof AuthedCookGenerateRoute
  '/cook/session': typeof AuthedCookSessionRoute
  '/pantry/$itemId': typeof AuthedPantryItemIdRoute
  '/pantry/new': typeof AuthedPantryNewRoute
  '/recipes/$recipeId': typeof AuthedRecipesRecipeIdRoute
  '/cook': typeof AuthedCookIndexRoute
  '/pantry': typeof AuthedPantryIndexRoute
  '/recipes': typeof AuthedRecipesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/home': typeof AuthedHomeRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/trial': typeof AuthedTrialRoute
  '/_authed/upgrade': typeof AuthedUpgradeRoute
  '/_authed/cook/generate': typeof AuthedCookGenerateRoute
  '/_authed/cook/session': typeof AuthedCookSessionRoute
  '/_authed/pantry/$itemId': typeof AuthedPantryItemIdRoute
  '/_authed/pantry/new': typeof AuthedPantryNewRoute
  '/_authed/recipes/$recipeId': typeof AuthedRecipesRecipeIdRoute
  '/_authed/cook/': typeof AuthedCookIndexRoute
  '/_authed/pantry/': typeof AuthedPantryIndexRoute
  '/_authed/recipes/': typeof AuthedRecipesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/home'
    | '/settings'
    | '/trial'
    | '/upgrade'
    | '/cook/generate'
    | '/cook/session'
    | '/pantry/$itemId'
    | '/pantry/new'
    | '/recipes/$recipeId'
    | '/cook/'
    | '/pantry/'
    | '/recipes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/home'
    | '/settings'
    | '/trial'
    | '/upgrade'
    | '/cook/generate'
    | '/cook/session'
    | '/pantry/$itemId'
    | '/pantry/new'
    | '/recipes/$recipeId'
    | '/cook'
    | '/pantry'
    | '/recipes'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/_authed/home'
    | '/_authed/settings'
    | '/_authed/trial'
    | '/_authed/upgrade'
    | '/_authed/cook/generate'
    | '/_authed/cook/session'
    | '/_authed/pantry/$itemId'
    | '/_authed/pantry/new'
    | '/_authed/recipes/$recipeId'
    | '/_authed/cook/'
    | '/_authed/pantry/'
    | '/_authed/recipes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/upgrade': {
      id: '/_authed/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof AuthedUpgradeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/trial': {
      id: '/_authed/trial'
      path: '/trial'
      fullPath: '/trial'
      preLoaderRoute: typeof AuthedTrialRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/home': {
      id: '/_authed/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthedHomeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/recipes/': {
      id: '/_authed/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof AuthedRecipesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/pantry/': {
      id: '/_authed/pantry/'
      path: '/pantry'
      fullPath: '/pantry/'
      preLoaderRoute: typeof AuthedPantryIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/cook/': {
      id: '/_authed/cook/'
      path: '/cook'
      fullPath: '/cook/'
      preLoaderRoute: typeof AuthedCookIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/recipes/$recipeId': {
      id: '/_authed/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof AuthedRecipesRecipeIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/pantry/new': {
      id: '/_authed/pantry/new'
      path: '/pantry/new'
      fullPath: '/pantry/new'
      preLoaderRoute: typeof AuthedPantryNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/pantry/$itemId': {
      id: '/_authed/pantry/$itemId'
      path: '/pantry/$itemId'
      fullPath: '/pantry/$itemId'
      preLoaderRoute: typeof AuthedPantryItemIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/cook/session': {
      id: '/_authed/cook/session'
      path: '/cook/session'
      fullPath: '/cook/session'
      preLoaderRoute: typeof AuthedCookSessionRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/cook/generate': {
      id: '/_authed/cook/generate'
      path: '/cook/generate'
      fullPath: '/cook/generate'
      preLoaderRoute: typeof AuthedCookGenerateRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedHomeRoute: typeof AuthedHomeRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedTrialRoute: typeof AuthedTrialRoute
  AuthedUpgradeRoute: typeof AuthedUpgradeRoute
  AuthedCookGenerateRoute: typeof AuthedCookGenerateRoute
  AuthedCookSessionRoute: typeof AuthedCookSessionRoute
  AuthedPantryItemIdRoute: typeof AuthedPantryItemIdRoute
  AuthedPantryNewRoute: typeof AuthedPantryNewRoute
  AuthedRecipesRecipeIdRoute: typeof AuthedRecipesRecipeIdRoute
  AuthedCookIndexRoute: typeof AuthedCookIndexRoute
  AuthedPantryIndexRoute: typeof AuthedPantryIndexRoute
  AuthedRecipesIndexRoute: typeof AuthedRecipesIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedHomeRoute: AuthedHomeRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedTrialRoute: AuthedTrialRoute,
  AuthedUpgradeRoute: AuthedUpgradeRoute,
  AuthedCookGenerateRoute: AuthedCookGenerateRoute,
  AuthedCookSessionRoute: AuthedCookSessionRoute,
  AuthedPantryItemIdRoute: AuthedPantryItemIdRoute,
  AuthedPantryNewRoute: AuthedPantryNewRoute,
  AuthedRecipesRecipeIdRoute: AuthedRecipesRecipeIdRoute,
  AuthedCookIndexRoute: AuthedCookIndexRoute,
  AuthedPantryIndexRoute: AuthedPantryIndexRoute,
  AuthedRecipesIndexRoute: AuthedRecipesIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
