/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedPantryRouteImport } from './routes/_authed/pantry'
import { Route as AuthedHomeRouteImport } from './routes/_authed/home'
import { Route as AuthedPantryNewRouteImport } from './routes/_authed/pantry.new'
import { Route as AuthedPantryItemIdRouteImport } from './routes/_authed/pantry.$itemId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedPantryRoute = AuthedPantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHomeRoute = AuthedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPantryNewRoute = AuthedPantryNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedPantryRoute,
} as any)
const AuthedPantryItemIdRoute = AuthedPantryItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => AuthedPantryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/home': typeof AuthedHomeRoute
  '/pantry': typeof AuthedPantryRouteWithChildren
  '/pantry/$itemId': typeof AuthedPantryItemIdRoute
  '/pantry/new': typeof AuthedPantryNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/home': typeof AuthedHomeRoute
  '/pantry': typeof AuthedPantryRouteWithChildren
  '/pantry/$itemId': typeof AuthedPantryItemIdRoute
  '/pantry/new': typeof AuthedPantryNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/home': typeof AuthedHomeRoute
  '/_authed/pantry': typeof AuthedPantryRouteWithChildren
  '/_authed/pantry/$itemId': typeof AuthedPantryItemIdRoute
  '/_authed/pantry/new': typeof AuthedPantryNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/home'
    | '/pantry'
    | '/pantry/$itemId'
    | '/pantry/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/home'
    | '/pantry'
    | '/pantry/$itemId'
    | '/pantry/new'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/_authed/home'
    | '/_authed/pantry'
    | '/_authed/pantry/$itemId'
    | '/_authed/pantry/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/pantry': {
      id: '/_authed/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof AuthedPantryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/home': {
      id: '/_authed/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthedHomeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/pantry/new': {
      id: '/_authed/pantry/new'
      path: '/new'
      fullPath: '/pantry/new'
      preLoaderRoute: typeof AuthedPantryNewRouteImport
      parentRoute: typeof AuthedPantryRoute
    }
    '/_authed/pantry/$itemId': {
      id: '/_authed/pantry/$itemId'
      path: '/$itemId'
      fullPath: '/pantry/$itemId'
      preLoaderRoute: typeof AuthedPantryItemIdRouteImport
      parentRoute: typeof AuthedPantryRoute
    }
  }
}

interface AuthedPantryRouteChildren {
  AuthedPantryItemIdRoute: typeof AuthedPantryItemIdRoute
  AuthedPantryNewRoute: typeof AuthedPantryNewRoute
}

const AuthedPantryRouteChildren: AuthedPantryRouteChildren = {
  AuthedPantryItemIdRoute: AuthedPantryItemIdRoute,
  AuthedPantryNewRoute: AuthedPantryNewRoute,
}

const AuthedPantryRouteWithChildren = AuthedPantryRoute._addFileChildren(
  AuthedPantryRouteChildren,
)

interface AuthedRouteChildren {
  AuthedHomeRoute: typeof AuthedHomeRoute
  AuthedPantryRoute: typeof AuthedPantryRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedHomeRoute: AuthedHomeRoute,
  AuthedPantryRoute: AuthedPantryRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
